from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, JSON, Text, Enum as SQLEnum
from sqlalchemy.orm import relationship
from datetime import datetime
from app.database.base import Base
import enum


class DifficultyLevel(str, enum.Enum):
    """Quiz difficulty levels"""
    EASY = "easy"
    MEDIUM = "medium"
    HARD = "hard"


class Company(Base):
    """Companies table - stores all companies offering placement tests"""
    __tablename__ = "companies"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), unique=True, nullable=False, index=True)  # TCS, Infosys, etc.
    description = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    quiz_levels = relationship("QuizLevel", back_populates="company", cascade="all, delete-orphan")
    questions = relationship("CompanyQuestion", back_populates="company", cascade="all, delete-orphan")
    quiz_sessions = relationship("QuizSession", back_populates="company", cascade="all, delete-orphan")


class QuizLevel(Base):
    """Quiz levels for each company (easy, medium, hard)"""
    __tablename__ = "quiz_levels"

    id = Column(Integer, primary_key=True, index=True)
    company_id = Column(Integer, ForeignKey("companies.id"), nullable=False)
    level = Column(SQLEnum(DifficultyLevel), nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    company = relationship("Company", back_populates="quiz_levels")
    questions = relationship("CompanyQuestion", back_populates="quiz_level", cascade="all, delete-orphan")
    quiz_sessions = relationship("QuizSession", back_populates="quiz_level", cascade="all, delete-orphan")


class CompanyQuestion(Base):
    """Questions generated by Gemini API for each company and level"""
    __tablename__ = "company_questions"

    id = Column(Integer, primary_key=True, index=True)
    company_id = Column(Integer, ForeignKey("companies.id"), nullable=False, index=True)
    level_id = Column(Integer, ForeignKey("quiz_levels.id"), nullable=False, index=True)
    question_text = Column(Text, nullable=False)
    options = Column(JSON, nullable=False)  # ["Option A", "Option B", "Option C", "Option D"]
    correct_answer = Column(String(500), nullable=False)
    explanation = Column(Text, nullable=True)
    source = Column(String(50), default="gemini")  # gemini, manual, etc.
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    
    # Relationships
    company = relationship("Company", back_populates="questions")
    quiz_level = relationship("QuizLevel", back_populates="questions")
    session_answers = relationship("SessionAnswer", back_populates="question", cascade="all, delete-orphan")


class QuizSession(Base):
    """User quiz sessions - tracks each quiz attempt"""
    __tablename__ = "quiz_sessions"

    id = Column(Integer, primary_key=True, index=True)
    company_id = Column(Integer, ForeignKey("companies.id"), nullable=False, index=True)
    level_id = Column(Integer, ForeignKey("quiz_levels.id"), nullable=False, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True, index=True)  # Nullable for guest users
    started_at = Column(DateTime, default=datetime.utcnow, index=True)
    completed_at = Column(DateTime, nullable=True)
    score = Column(Integer, nullable=True)  # Filled after submission
    total_questions = Column(Integer, nullable=False)
    status = Column(String(20), default="active")  # active, completed, abandoned
    
    # Relationships
    company = relationship("Company", back_populates="quiz_sessions")
    quiz_level = relationship("QuizLevel", back_populates="quiz_sessions")
    user = relationship("User")
    answers = relationship("SessionAnswer", back_populates="session", cascade="all, delete-orphan")


class SessionAnswer(Base):
    """User answers for each question in a quiz session"""
    __tablename__ = "session_answers"

    id = Column(Integer, primary_key=True, index=True)
    session_id = Column(Integer, ForeignKey("quiz_sessions.id"), nullable=False, index=True)
    question_id = Column(Integer, ForeignKey("company_questions.id"), nullable=False, index=True)
    selected_answer = Column(String(500), nullable=True)  # User's selected answer
    is_correct = Column(Integer, nullable=True)  # 1 for correct, 0 for incorrect
    answered_at = Column(DateTime, nullable=True)
    
    # Relationships
    session = relationship("QuizSession", back_populates="answers")
    question = relationship("CompanyQuestion", back_populates="session_answers")
