"""describe change

Revision ID: fca40f3a9821
Revises: d50cb9ea5035
Create Date: 2026-01-23 18:35:17.882470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fca40f3a9821'
down_revision: Union[str, Sequence[str], None] = 'd50cb9ea5035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_levels_id'), table_name='quiz_levels')
    op.drop_table('quiz_levels')
    op.drop_index(op.f('ix_company_questions_company_id'), table_name='company_questions')
    op.drop_index(op.f('ix_company_questions_created_at'), table_name='company_questions')
    op.drop_index(op.f('ix_company_questions_id'), table_name='company_questions')
    op.drop_index(op.f('ix_company_questions_level_id'), table_name='company_questions')
    op.drop_table('company_questions')
    op.drop_index(op.f('ix_questions_company'), table_name='questions')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_quiz_sessions_company_id'), table_name='quiz_sessions')
    op.drop_index(op.f('ix_quiz_sessions_id'), table_name='quiz_sessions')
    op.drop_index(op.f('ix_quiz_sessions_level_id'), table_name='quiz_sessions')
    op.drop_index(op.f('ix_quiz_sessions_started_at'), table_name='quiz_sessions')
    op.drop_index(op.f('ix_quiz_sessions_user_id'), table_name='quiz_sessions')
    op.drop_table('quiz_sessions')
    op.drop_index(op.f('ix_session_answers_id'), table_name='session_answers')
    op.drop_index(op.f('ix_session_answers_question_id'), table_name='session_answers')
    op.drop_index(op.f('ix_session_answers_session_id'), table_name='session_answers')
    op.drop_table('session_answers')
    op.drop_index(op.f('ix_user_answers_id'), table_name='user_answers')
    op.drop_table('user_answers')
    op.add_column('quiz_results', sa.Column('answers', sa.JSON(), nullable=False))
    op.add_column('quiz_results', sa.Column('submitted_at', sa.DateTime(), nullable=True))
    op.alter_column('quiz_results', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('quiz_results', 'percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('ix_quiz_results_created_at'), table_name='quiz_results')
    op.create_index(op.f('ix_quiz_results_submitted_at'), 'quiz_results', ['submitted_at'], unique=False)
    op.drop_column('quiz_results', 'created_at')
    op.add_column('quizzes', sa.Column('company', sa.String(), nullable=False))
    op.add_column('quizzes', sa.Column('track', sa.String(), nullable=False))
    op.add_column('quizzes', sa.Column('exam_type', sa.String(), nullable=False))
    op.add_column('quizzes', sa.Column('category', sa.String(), nullable=False))
    op.add_column('quizzes', sa.Column('topic', sa.String(), nullable=False))
    op.add_column('quizzes', sa.Column('difficulty', sa.String(), nullable=False))
    op.add_column('quizzes', sa.Column('question_type', sa.String(), nullable=False))
    op.add_column('quizzes', sa.Column('question_count', sa.Integer(), nullable=False))
    op.add_column('quizzes', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_quizzes_company'), 'quizzes', ['company'], unique=False)
    op.create_index(op.f('ix_quizzes_created_at'), 'quizzes', ['created_at'], unique=False)
    op.create_index(op.f('ix_quizzes_id'), 'quizzes', ['id'], unique=False)
    op.create_index(op.f('ix_quizzes_topic'), 'quizzes', ['topic'], unique=False)
    op.drop_column('quizzes', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_quizzes_topic'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_id'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_created_at'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_company'), table_name='quizzes')
    op.drop_column('quizzes', 'created_at')
    op.drop_column('quizzes', 'question_count')
    op.drop_column('quizzes', 'question_type')
    op.drop_column('quizzes', 'difficulty')
    op.drop_column('quizzes', 'topic')
    op.drop_column('quizzes', 'category')
    op.drop_column('quizzes', 'exam_type')
    op.drop_column('quizzes', 'track')
    op.drop_column('quizzes', 'company')
    op.add_column('quiz_results', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_quiz_results_submitted_at'), table_name='quiz_results')
    op.create_index(op.f('ix_quiz_results_created_at'), 'quiz_results', ['created_at'], unique=False)
    op.alter_column('quiz_results', 'percentage',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('quiz_results', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('quiz_results', 'submitted_at')
    op.drop_column('quiz_results', 'answers')
    op.create_table('user_answers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('quiz_result_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('selected_answer', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_correct', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('user_answers_question_id_fkey')),
    sa.ForeignKeyConstraint(['quiz_result_id'], ['quiz_results.id'], name=op.f('user_answers_quiz_result_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_answers_pkey'))
    )
    op.create_index(op.f('ix_user_answers_id'), 'user_answers', ['id'], unique=False)
    op.create_table('session_answers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('selected_answer', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_correct', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['company_questions.id'], name=op.f('session_answers_question_id_fkey')),
    sa.ForeignKeyConstraint(['session_id'], ['quiz_sessions.id'], name=op.f('session_answers_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('session_answers_pkey'))
    )
    op.create_index(op.f('ix_session_answers_session_id'), 'session_answers', ['session_id'], unique=False)
    op.create_index(op.f('ix_session_answers_question_id'), 'session_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_session_answers_id'), 'session_answers', ['id'], unique=False)
    op.create_table('quiz_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('level_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_questions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('quiz_sessions_company_id_fkey')),
    sa.ForeignKeyConstraint(['level_id'], ['quiz_levels.id'], name=op.f('quiz_sessions_level_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('quiz_sessions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('quiz_sessions_pkey'))
    )
    op.create_index(op.f('ix_quiz_sessions_user_id'), 'quiz_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_quiz_sessions_started_at'), 'quiz_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_quiz_sessions_level_id'), 'quiz_sessions', ['level_id'], unique=False)
    op.create_index(op.f('ix_quiz_sessions_id'), 'quiz_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_quiz_sessions_company_id'), 'quiz_sessions', ['company_id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('companies_pkey'))
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('track', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('exam_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('question_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('correct_answer', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('explanation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('approved', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('questions_pkey')),
    sa.UniqueConstraint('question', name=op.f('questions_question_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_index(op.f('ix_questions_company'), 'questions', ['company'], unique=False)
    op.create_table('company_questions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('level_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('correct_answer', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('explanation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('company_questions_company_id_fkey')),
    sa.ForeignKeyConstraint(['level_id'], ['quiz_levels.id'], name=op.f('company_questions_level_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('company_questions_pkey'))
    )
    op.create_index(op.f('ix_company_questions_level_id'), 'company_questions', ['level_id'], unique=False)
    op.create_index(op.f('ix_company_questions_id'), 'company_questions', ['id'], unique=False)
    op.create_index(op.f('ix_company_questions_created_at'), 'company_questions', ['created_at'], unique=False)
    op.create_index(op.f('ix_company_questions_company_id'), 'company_questions', ['company_id'], unique=False)
    op.create_table('quiz_levels',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('level', postgresql.ENUM('EASY', 'MEDIUM', 'HARD', name='difficultylevel'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('quiz_levels_company_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('quiz_levels_pkey'))
    )
    op.create_index(op.f('ix_quiz_levels_id'), 'quiz_levels', ['id'], unique=False)
    # ### end Alembic commands ###
